export const testimonials = [
  {
    id: 0,
    userPhoto: 'src/img/testimonials/man.png',
    photo: '',
    userName: 'Michael John',
    userLocation: 'Local Austria',
    day: 'Today',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 1,
    userPhoto: 'src/img/testimonials/oscar.png',
    userName: 'Oskar Samborsky',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 2,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'Fredericka Michelin',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 3,
    userPhoto: 'src/img/testimonials/mila.png',
    userName: 'Mila Riksha',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 4,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'User4',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 5,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'User5',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 6,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'User5',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 7,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'User5',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 8,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'User5',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 9,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'User5',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 10,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'User5',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    id: 11,
    userPhoto: 'src/img/testimonials/fredericka.png',
    userName: 'User5',
    userLocation: 'Local Austria',
    day: 'Yesterday',
    text: 'The best online zoo I’ve met. My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.The best online zoo I’vemet. My son delighted very much ljves to watch gouillas. Online zoo is one jf the waysto instill a love for animals. <br />The best online zoo I’ve met. My son delightedvery much ljves to watch gouillas. Online zoo is one jf the ways to instill a love foranimals.The best online zoo I’ve met. My son delighted very much ljves to watchgouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
];
